### ISSUE TITLE
API documentation missing

### ISSUE THREAD

**Issue by christophfriedrich** [fs-geofs/UserManager#5]
I would like to implement #1 but don't know in which format the endpoints expect their input. I tried to guess it by looking at the source code but failed with various attempts, I always get `Error parsing Request Body: Error parsing User to struct`. (Needless to say that that's a very inconvenient method to get this information anyway.) Can you please add documentation for the API? Sample snippets would be enough.

**Comment by noerw** [comment]
There is documentation in the Open API format [here](https://raw.githubusercontent.com/fs-geofs/UserManager/master/userManagerAPI.yaml)
You can explore it more easily on a site like [this](https://mrin9.github.io/OpenAPI-Viewer/)

Are there examples missing?

**Comment by christophfriedrich** [comment]
Oh, I didn't know that file yet. That's a big improvement already! 👍

What's missing is how to supply the username + Fachschaft. E.g. for me is it "christoph" or "fsgi.christoph" or "cn=christoph,o=fsgi" (*) or do I have to supply another property called `fs` (**) or noch was ganz anderes?

(*) this seemed the most logical variant for me because `/api/users/list` supplies the names in this format, but it didn't work when I tried.

(**) this is how it's done in `/api/users/add` and `api/users/remove`, but it didn't work either

**Comment by SpeckiJ** [comment]
> What's missing is how to supply the username + Fachschaft

Why do you want to supply the Fachschaft? Does it not work when just specifying username + group as described in the docs?

I have just tested it and it seems to work fine for me. What error message do you get when just supplying "username" and "group" as described in the docs?

**Comment by christophfriedrich** [comment]
> Does it not work when just specifying username + group as described in the docs?

No, just supplying the username didn't work.

But now I found the error: My payload JSON had the property named `groupname`, not `group`. After fixing that it works fine with just the username 👍 I never looked for the mistake there because the error message was nevertheless: "Error parsing Request Body: Error parsing User to struct" 🤔

> Why do you want to supply the Fachschaft?

To me it seemed logical that I had to supply the Fachschaft because the removeUser and changePassword endpoints require it too. Why is it needed there but not here?

**Comment by SpeckiJ** [comment]
> when just specifying username + group as described in the docs
> > No, just supplying the username didn't work.

:laughing: so not as described in the docs 


> I never looked for the mistake there because the error message was nevertheless: "Error parsing Request Body: Error parsing User to struct"

Which is the correct error, since the User that has been parsed from the request failed validation as it misses a required field ("group") (Further details below).


> [...] because the removeUser and changePassword endpoints require it too

This stems from the fact that the backend differs between ["GroupUser"](https://github.com/fs-geofs/UserManager/blob/7eb2a8ea7214a85afae4baf6431dc3efc8809844/structs.go#L25) which is a combination of username and group association and ["User"](https://github.com/fs-geofs/UserManager/blob/7eb2a8ea7214a85afae4baf6431dc3efc8809844/structs.go#L19), which has a password and fachschaft.

At the moment of programming this seemed to be the best option, as we can do proper validation now when initializing the structs. If all properties would be in a single struct, they would often be nil and validation becomes more difficult (what properties are needed for this specific request? does password need to be set now? Or is it a groupAdd request that does not have a password? )


Will close this issue as it has been solved and the documentation is now known to all developers.

**Comment by christophfriedrich** [comment]
> 😆 so not as described in the docs

Yes, I admit that 😇

but...

> Which is the correct error

I very much contest this - a user and a group are two different things; I wouldn't expect the latter to be a property of the former.

**Comment by christophfriedrich** [comment]
> Are there examples missing?

I came across one more when I saw `sha512` in the frontend code again: The docs don't state in which way the password should be submitted (the user could expect cleartext or some other hash method just as well).

**Comment by SpeckiJ** [comment]
Merged with https://github.com/fs-geofs/UserManager/pull/10
